--- #YAML:1.0
name:               Net-HTTPS-NB
version:            0.11
abstract:           Non-blocking HTTPS client
author:
    - Oleg G <oleg@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Exporter:         0
    IO::Socket::SSL:  0.98
    Net::HTTP:        0
    Net::HTTPS:       0
resources:
    repository:  https://github.com/olegwtf/p5-Net-HTTPS-NB
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
